FROM node:18-alpine
ENV NODE_ENV development
RUN npm i pnpm -g

WORKDIR /app

COPY ../package.json ./
COPY ../pnpm-lock.yaml ./
COPY ../.npmrc ./

RUN pnpm install

COPY ../ ./

RUN pnpm build

EXPOSE 80

CMD ["pnpm", "run", "dev"]
