name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run format

